name: Pypi Publishing

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-test-[0-9]+'

jobs:
  publish:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine

    - name: Build and publish
      # This step adapted from https://realpython.com/pypi-publish-python-package/
      env:
        TWINE_USERNAME: ${{ secrets.pcic_at_pypi_username }}
        TWINE_PASSWORD: ${{ secrets.pcic_at_pypi_password }}
      run: |
        python -m build
        twine upload --repository-url https://pypi.pacificclimate.org/ --skip-existing -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*
