name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      run: |
        pip install -U pipenv==2022.3.28

    - name: Install OS dependencies
      run: |
        sudo apt update
        sudo apt install libxml2-dev libxslt-dev python-dev
        sudo apt purge postgresql-client-14 postgresql-server-dev-all
        sudo apt install postgresql-12-postgis-3

    - id: cache-pipenv
      name: Cache pipenv
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies if changed
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      env:
        PIP_INDEX_URL: https://pypi.pacificclimate.org/simple
      run: |
        pipenv install --deploy --dev
        pipenv run pip install .

    - name: Test with pytest
      env:
        TZ: Canada/Pacific
      run: |
        pipenv run pytest -m "not online" -v --tb=short --cov --cov-report=term-missing

    - name: Code format check
      run: pipenv run black . --check
